name: Cling Build and Test (Windows)

on:
  push:
    paths:
      - '**'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout LLVM
        uses: actions/checkout@v6
        with:
          repository: root-project/llvm-project
          path: llvm-project
          ref: cling-latest
          fetch-depth: 1

      - name: Checkout Cling
        uses: actions/checkout@v6
        with:
          repository: root-project/cling
          path: cling
          fetch-depth: 1

      - name: Build Cling
        shell: pwsh
        run: |
          $env:ncpus = $([Environment]::ProcessorCount)
          $env:PWD_DIR = $PWD.Path
          $env:CLING_DIR = "$env:PWD_DIR\cling"

          New-Item -ItemType Directory -Force -Path llvm-project\build | Out-Null
          Set-Location llvm-project\build

          cmake -DLLVM_ENABLE_PROJECTS=clang `
                -DLLVM_EXTERNAL_PROJECTS=cling `
                -DLLVM_EXTERNAL_CLING_SOURCE_DIR="$env:CLING_DIR" `
                -DLLVM_TARGETS_TO_BUILD="host;NVPTX" `
                -DCMAKE_BUILD_TYPE=RelWithDebInfo `
                -DLLVM_ENABLE_ASSERTIONS=ON `
                ../llvm

          cmake --build . --target clang --parallel $env:ncpus
          cmake --build . --target cling --parallel $env:ncpus

      # - name: Test
      #   working-directory: build
      #   run: cmake --build . --config RelWithDebInfo --target check-cling

      - name: Install
        shell: pwsh
        run: |
          $env:PWD_DIR = $PWD.Path
          cmake --install "$env:PWD_DIR\llvm-project\build" --prefix "$env:PWD_DIR\install" --config RelWithDebInfo

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cling-windows
          path: install/
